[package]
name = "rust-8-desktop"
version = "0.0.1"
authors = ["Ryan Levick <ryan.levick@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.105.0"
random-trait= "0.1.1"
random-fast-rng = "0.1.1"
[dependencies.rust-8]
path = "../chip8"
